# Generated by Django 3.0.3 on 2020-03-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200312_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateuncoveredacc',
            name='uncovered',
            field=models.BooleanField(default=False),
        ),
    ]
