# Generated by Django 3.0.3 on 2020-03-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_privateuncoveredacc_uncovered'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateuncoveredphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='privateuncoveredphoto',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
