# Generated by Django 3.0.3 on 2020-03-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200313_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosArchive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('img_link', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
