# Generated by Django 3.0.3 on 2020-03-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_accountarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stalked_Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stalked_account', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('on_user', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Unfollow',
            new_name='WhoUnfollowed_StalkedProf',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
