# Generated by Django 3.0.3 on 2020-03-25 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_auto_20200325_1533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stalked_Action',
            new_name='StalkedAction',
        ),
        migrations.RenameModel(
            old_name='WhoUnfollowed_StalkedProf',
            new_name='WhoUnfollowedStalkedProf',
        ),
    ]
