# Generated by Django 3.0.3 on 2020-03-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200325_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='stalkedaction',
            name='pic',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
